import type { Step } from '@/types/triagem';

export const perguntasTriagemGeralRapida: Step[] = [
  {
    type: 'intro',
    name: 'intro',
    label: 'Triagem Rápida de Saúde Geral',
    justification: `Responda essas perguntas essenciais para uma avaliação rápida do seu estado de saúde. Ideal para orientações iniciais em até 5 minutos.`,
  },
  {
    type: 'select',
    name: 'sexo',
    label: 'Qual seu sexo biológico?',
    options: ['Masculino', 'Feminino'],
    required: true,
  },
  {
    type: 'text',
    name: 'dataNascimento',
    label: 'Data de nascimento',
    placeholder: 'DD/MM/AAAA',
    required: true,
  },
  {
    type: 'text',
    name: 'peso_altura',
    label: 'Informe seu peso e altura aproximados (kg e cm)',
    placeholder: 'Ex: 70 kg, 170 cm',
    required: true,
  },
  {
    type: 'select',
    name: 'estresse',
    label: 'Como está seu nível de estresse hoje?',
    options: ['Baixo', 'Moderado', 'Alto'],
    required: true,
  },
  {
    type: 'select',
    name: 'humor',
    label: 'Como descreveria seu humor recente?',
    options: ['Estável', 'Ansioso', 'Triste', 'Irritado'],
    required: true,
  },
  {
    type: 'select',
    name: 'atividade_fisica',
    label: 'Você pratica atividade física?',
    options: ['Não', '1-2x/semana', '3-4x/semana', '5x ou mais'],
    required: true,
  },
  {
    type: 'select',
    name: 'qualidade_sono',
    label: 'Como você avalia seu sono?',
    options: ['Bom', 'Regular', 'Ruim'],
    required: true,
  },
  {
    type: 'select',
    name: 'alimentacao',
    label: 'Sua alimentação inclui frutas, vegetais e proteínas?',
    options: ['Sim, diariamente', 'Às vezes', 'Quase nunca'],
    required: true,
  },
  {
    type: 'select',
    name: 'ultraprocessados',
    label: 'Consome alimentos ultraprocessados?',
    options: ['Raramente', '1-2x/semana', '3x ou mais por semana'],
    required: true,
  },
  {
    type: 'select',
    name: 'alcool_tabaco',
    label: 'Consome álcool ou tabaco?',
    options: ['Não', 'Álcool', 'Tabaco', 'Ambos'],
    required: true,
  },
  {
    type: 'select',
    name: 'suplementacao',
    label: 'Usa suplementos vitamínicos?',
    options: ['Não', 'Sim, regularmente', 'Sim, ocasionalmente'],
    required: true,
  },
  {
    type: 'select',
    name: 'medicamentos',
    label: 'Faz uso de medicamentos?',
    options: ['Não', 'Sim, contínuo', 'Sim, esporádico'],
    required: true,
  },
  {
    type: 'select',
    name: 'doenca_cronica',
    label: 'Tem alguma doença crônica?',
    options: ['Não', 'Sim, uma', 'Sim, mais de uma'],
    required: true,
  },
  {
    type: 'select',
    name: 'checkup',
    label: 'Você faz checkups médicos?',
    options: ['Anualmente', 'Ocasionalmente', 'Nunca'],
    required: true,
  },
  {
    type: 'select',
    name: 'objetivo_saude',
    label: 'Qual seu maior objetivo de saúde atual?',
    options: [
      'Emagrecer',
      'Ganho de massa',
      'Melhorar sono',
      'Reduzir estresse',
      'Outro',
    ],
    required: true,
  },
  {
    type: 'select',
    name: 'exames_recentes',
    label: 'Fez exames nos últimos 12 meses?',
    options: ['Sim, completos', 'Sim, básicos', 'Não'],
    required: true,
  },
];

export const triagemGeralRapidaSteps: Step[] = perguntasTriagemGeralRapida;