import type { Step } from '@/types/triagem';
import { stepAceitaTermos } from '../shared/consentimento';
import { stepIdadeFaixa, stepSexo } from '../shared/dadosBasicos';

export const perguntasAnsiedade: Step[] = [
  stepAceitaTermos,
  stepIdadeFaixa,
  stepSexo,
  {
    name: 'sintomas_principais',
    type: 'multiselect',
    label: 'Quais sintomas de ansiedade você apresenta?',
    options: [
      { value: 'Preocupação excessiva', label: 'Preocupação excessiva' },
      { value: 'Nervosismo constante', label: 'Nervosismo constante' },
      { value: 'Taquicardia/palpitações', label: 'Taquicardia/palpitações' },
      { value: 'Falta de ar/sensação de sufocamento', label: 'Falta de ar/sensação de sufocamento' },
      { value: 'Tensão muscular', label: 'Tensão muscular' },
      { value: 'Insônia relacionada à ansiedade', label: 'Insônia relacionada à ansiedade' },
    ],
    required: true,
    helperText: 'Escolha todos os sintomas que você sente.',
    justification: 'Sintomas ajudam a identificar padrão e gravidade.',
  },
  {
    name: 'frequencia_ansiedade',
    type: 'select',
    label: 'Com que frequência você sente ansiedade?',
    options: [
      { value: 'Diariamente', label: 'Diariamente' },
      { value: 'Várias vezes por semana', label: 'Várias vezes por semana' },
      { value: 'Uma vez por semana', label: 'Uma vez por semana' },
      { value: 'Ocasionalmente', label: 'Ocasionalmente' },
    ],
    required: true,
    helperText: 'Frequência ajuda a entender o impacto na sua vida.',
    justification: 'Frequência é critério importante para tratamento.',
  },
  {
    name: 'impacto_funcional',
    type: 'select',
    label: 'Como a ansiedade afeta seu dia a dia?',
    options: [
      { value: 'Não afeta muito', label: 'Não afeta muito' },
      { value: 'Afeta algumas atividades', label: 'Afeta algumas atividades' },
      { value: 'Afeta bastante meu trabalho/estudos', label: 'Afeta bastante meu trabalho/estudos' },
      { value: 'Afeta muito minha qualidade de vida', label: 'Afeta muito minha qualidade de vida' },
    ],
    required: true,
    helperText: 'Impacto funcional ajuda a calibrar urgência do tratamento.',
    justification: 'Impacto funcional é crucial para tipo e intensidade de tratamento.',
  },
  {
    name: 'historico_tratamento',
    type: 'select',
    label: 'Você já fez tratamento para ansiedade?',
    options: [
      { value: 'Sim, terapia psicológica', label: 'Sim, terapia psicológica' },
      { value: 'Sim, medicação', label: 'Sim, medicação' },
      { value: 'Sim, ambos', label: 'Sim, ambos' },
      { value: 'Não', label: 'Não' },
    ],
    required: true,
    helperText: 'Histórico ajuda a não repetir o que não funcionou.',
    justification: 'Histórico orienta o relatório a propor caminhos adequados.',
  },
  {
    name: 'info_contraindicacoes_ansiedade',
    type: 'info',
    icon: '🛡️',
    highlightTag: 'Segurança',
    label: 'Algumas condições precisam de avaliação especial',
    description: 'Vamos verificar se há algo que exija cuidado antes do tratamento:',
    bullets: [
      'Seu relatório será personalizado com base nas suas respostas.',
      'Em caso de dúvida, o médico avaliará no momento da consulta.',
    ],
    justification: 'Educação e segurança antes de contraindicações.',
  },
  {
    name: 'contraindicacoes_ansiedade',
    type: 'multiselect',
    label: 'Você tem ou já teve alguma dessas condições?',
    options: [
      { value: 'depressao_grave', label: 'Depressão grave ou ideação suicida' },
      { value: 'bipolar', label: 'Transtorno bipolar' },
      { value: 'alcool_substancias', label: 'Uso problemático de álcool ou substâncias' },
      { value: 'gestacao_amamentacao', label: 'Gestação ou amamentação' },
      { value: 'alergia_fitoterapicos', label: 'Alergia a passiflora, valeriana ou similares' },
      { value: 'nenhuma', label: 'Nenhuma dessas' },
    ],
    required: true,
    helperText: 'Essas informações são essenciais para sua segurança.',
    justification: 'Critério de segurança para tratamento de ansiedade.',
  },
  {
    name: 'preferencia_ansiedade',
    type: 'select_cards',
    label: 'Se precisar de tratamento, qual abordagem te parece melhor?',
    helperText: 'É só uma preferência inicial. A decisão final será sempre do médico.',
    required: true,
    justification: 'Usada pela IA para personalizar o relatório e recomendações.',
    cardOptions: [
      {
        value: 'fitoterapicos',
        title: 'Fitoterápicos (passiflora, valeriana)',
        subtitle: 'Abordagem natural para ansiedade leve a moderada.',
        badge: '🌿 Abordagem natural',
      },
      {
        value: 'terapia_suplementos',
        title: 'Terapia + suplementos',
        subtitle: 'Combinação de acompanhamento psicológico e suplementação.',
        badge: '💚 Integrativa',
      },
      {
        value: 'avaliacao_medica',
        title: 'Avaliação médica completa',
        subtitle: 'Quero que o médico avalie e indique o melhor tratamento.',
        badge: '🩺 Decisão guiada',
      },
      {
        value: 'nao_sei',
        title: 'Prefiro que o médico escolha',
        subtitle: 'Quero que o especialista indique a melhor opção.',
        badge: '✨ Recomendação do médico',
      },
    ],
  },
  {
    name: 'info_acompanhamento',
    type: 'info',
    icon: '🤝',
    highlightTag: 'Segurança e apoio',
    label: 'Você não faz esse caminho sozinho',
    description:
      'Tratamentos para ansiedade funcionam melhor quando combinam abordagens psicológicas, suplementação e acompanhamento médico.',
    bullets: [
      'Fitoterápicos como passiflora e valeriana ajudam a regular ansiedade',
      'Acompanhamento médico garante tratamento adequado e seguro',
    ],
    justification: 'Reforça segurança e autoridade médica.',
  },
];
