import type { Step } from '@/types/triagem';
import { stepAceitaTermos } from '../shared/consentimento';
import { stepIdadeFaixa, stepSexo } from '../shared/dadosBasicos';

export const perguntasArticulacoes: Step[] = [
  stepAceitaTermos,
  stepIdadeFaixa,
  stepSexo,
  {
    name: 'localizacao_dor',
    type: 'multiselect',
    label: 'Onde você sente dor ou desconforto?',
    options: [
      { value: 'Joelhos', label: 'Joelhos' },
      { value: 'Coluna (costas)', label: 'Coluna (costas)' },
      { value: 'Ombros', label: 'Ombros' },
      { value: 'Quadris', label: 'Quadris' },
      { value: 'Punhos/mãos', label: 'Punhos/mãos' },
      { value: 'Tornozelos/pés', label: 'Tornozelos/pés' },
      { value: 'Pescoço', label: 'Pescoço' },
    ],
    required: true,
    helperText: 'Escolha todas as áreas afetadas.',
    justification: 'Localização ajuda a identificar padrão e possíveis causas.',
  },
  {
    name: 'intensidade_dor',
    type: 'select',
    label: 'Como você avalia a intensidade da dor?',
    options: [
      { value: 'Leve (desconforto ocasional)', label: 'Leve (desconforto ocasional)' },
      { value: 'Moderada (dor frequente)', label: 'Moderada (dor frequente)' },
      { value: 'Intensa (dor constante)', label: 'Intensa (dor constante)' },
      { value: 'Muito intensa (limita atividades)', label: 'Muito intensa (limita atividades)' },
    ],
    required: true,
    helperText: 'Intensidade ajuda a calibrar urgência do tratamento.',
    justification: 'Intensidade é marcador importante de gravidade.',
  },
  {
    name: 'tempo_dor',
    type: 'select',
    label: 'Há quanto tempo você sente essas dores?',
    options: [
      { value: 'Menos de 1 mês', label: 'Menos de 1 mês' },
      { value: '1-3 meses', label: '1–3 meses' },
      { value: '3-6 meses', label: '3–6 meses' },
      { value: 'Mais de 6 meses', label: 'Mais de 6 meses' },
      { value: 'Anos', label: 'Anos' },
    ],
    required: true,
    helperText: 'Tempo ajuda a diferenciar dor aguda de crônica.',
    justification: 'Tempo de evolução orienta tipo de tratamento.',
  },
  {
    name: 'diagnostico_previo',
    type: 'select',
    label: 'Você já foi diagnosticado com artrose ou artrite?',
    options: [
      { value: 'Sim, artrose', label: 'Sim, artrose' },
      { value: 'Sim, artrite', label: 'Sim, artrite' },
      { value: 'Não sei', label: 'Não sei' },
      { value: 'Não', label: 'Não' },
    ],
    required: true,
    helperText: 'Diagnóstico prévio orienta tratamento.',
    justification: 'Diagnóstico prévio é importante para tratamento adequado.',
  },
  {
    name: 'info_contraindicacoes_articulacoes',
    type: 'info',
    icon: '🛡️',
    highlightTag: 'Segurança',
    label: 'Algumas condições precisam de avaliação especial',
    description: 'Vamos verificar se há algo que exija cuidado antes do tratamento:',
    bullets: [
      'Seu relatório será personalizado com base nas suas respostas.',
      'Em caso de dúvida, o médico avaliará no momento da consulta.',
    ],
    justification: 'Educação e segurança antes de contraindicações.',
  },
  {
    name: 'contraindicacoes_articulacoes',
    type: 'multiselect',
    label: 'Você tem ou já teve alguma dessas condições?',
    options: [
      { value: 'artrite_reumatóide', label: 'Artrite reumatóide ativa' },
      { value: 'gota', label: 'Gota em crise' },
      { value: 'alergia_colageno', label: 'Alergia conhecida a colágeno' },
      { value: 'doenca_renal', label: 'Doença renal grave' },
      { value: 'gestacao_amamentacao', label: 'Gestação ou amamentação' },
      { value: 'nenhuma', label: 'Nenhuma dessas' },
    ],
    required: true,
    helperText: 'Essas informações são essenciais para sua segurança.',
    justification: 'Critério de segurança para tratamento articular.',
  },
  {
    name: 'preferencia_articulacoes',
    type: 'select_cards',
    label: 'Se precisar de tratamento, qual abordagem te parece melhor?',
    helperText: 'É só uma preferência inicial. A decisão final será sempre do médico.',
    required: true,
    justification: 'Usada pela IA para personalizar o relatório e recomendações.',
    cardOptions: [
      {
        value: 'colageno',
        title: 'Colágeno tipo II',
        subtitle: 'Mantém integridade da cartilagem articular.',
        badge: '🦴 Evidência consolidada',
      },
      {
        value: 'antiinflamatorios',
        title: 'Anti-inflamatórios naturais',
        subtitle: 'Reduzem dor e inflamação sem efeitos colaterais.',
        badge: '🌿 Abordagem natural',
      },
      {
        value: 'combinado',
        title: 'Colágeno + anti-inflamatórios',
        subtitle: 'Abordagem integrativa para melhores resultados.',
        badge: '⚡ Potencial máximo',
      },
      {
        value: 'nao_sei',
        title: 'Prefiro que o médico escolha',
        subtitle: 'Quero que o especialista indique a melhor opção.',
        badge: '🩺 Decisão guiada',
      },
    ],
  },
  {
    name: 'info_acompanhamento',
    type: 'info',
    icon: '🤝',
    highlightTag: 'Segurança e apoio',
    label: 'Você não faz esse caminho sozinho',
    description:
      'Tratamentos articulares funcionam melhor quando combinam colágeno, anti-inflamatórios naturais e acompanhamento médico.',
    bullets: [
      'Colágeno tipo II mantém integridade articular',
      'Acompanhamento médico identifica causas e ajusta tratamento',
    ],
    justification: 'Reforça segurança e autoridade médica.',
  },
];
