import type { Step } from '@/types/triagem';
import { stepAceitaTermos } from '../shared/consentimento';
import { stepIdadeFaixa, stepSexo } from '../shared/dadosBasicos';

export const perguntasCalvicie: Step[] = [
  stepAceitaTermos,
  stepIdadeFaixa,
  stepSexo,
  {
    name: 'objetivo_capilar',
    type: 'select',
    label: 'Qual é seu principal objetivo?',
    options: [
      { value: 'Reduzir queda de cabelo', label: 'Reduzir queda de cabelo' },
      { value: 'Fortalecer fios existentes', label: 'Fortalecer fios existentes' },
      { value: 'Recuperar volume e densidade', label: 'Recuperar volume e densidade' },
      { value: 'Prevenir calvície futura', label: 'Prevenir calvície futura' },
      { value: 'Todos os anteriores', label: 'Todos os anteriores' },
    ],
    required: true,
    helperText: 'Escolha o que mais importa para você no momento.',
    justification: 'Definir o objetivo ajuda a IA a ajustar o foco do relatório.',
  },
  {
    name: 'tempo_queda',
    type: 'select',
    label: 'Há quanto tempo você percebe queda de cabelo?',
    options: [
      { value: 'Menos de 3 meses', label: 'Menos de 3 meses' },
      { value: '3-6 meses', label: '3–6 meses' },
      { value: '6 meses - 1 ano', label: '6 meses a 1 ano' },
      { value: 'Mais de 1 ano', label: 'Mais de 1 ano' },
      { value: 'Não tenho queda, só quero prevenir', label: 'Não tenho queda, só quero prevenir' },
    ],
    required: true,
    helperText: 'Isso ajuda a entender se é algo recente ou crônico.',
    evidenceNote: 'Tempo de evolução diferencia causas agudas de crônicas.',
    justification: 'Tempo de evolução ajuda a calibrar tratamento.',
  },
  {
    name: 'historico_familiar',
    type: 'select',
    label: 'Há histórico de calvície na família?',
    options: [
      { value: 'Sim, pai e avô', label: 'Sim, pai e avô' },
      { value: 'Sim, apenas pai', label: 'Sim, apenas pai' },
      { value: 'Sim, apenas avô', label: 'Sim, apenas avô' },
      { value: 'Sim, mãe/lado materno', label: 'Sim, mãe/lado materno' },
      { value: 'Não sei', label: 'Não sei' },
      { value: 'Não', label: 'Não' },
    ],
    required: true,
    helperText: 'A calvície androgenética tem forte componente genético.',
    evidenceNote: 'História familiar aumenta o risco de calvície androgenética.',
    justification: 'História familiar é fator de risco importante.',
  },
  {
    name: 'tratamentos_anteriores',
    type: 'multiselect',
    label: 'O que você já tentou para queda de cabelo?',
    options: [
      { value: 'Shampoos anticaspa', label: 'Shampoos anticaspa' },
      { value: 'Minoxidil', label: 'Minoxidil' },
      { value: 'Suplementos vitamínicos', label: 'Suplementos vitamínicos' },
      { value: 'Tratamentos capilares/química', label: 'Tratamentos capilares/química' },
      { value: 'Nada ainda', label: 'Nada ainda' },
    ],
    required: true,
    helperText: 'Sem julgamento – isso nos ajuda a não repetir o que não funcionou.',
    justification: 'Histórico orienta o relatório a propor caminhos diferentes.',
  },
  {
    name: 'localizacao_queda',
    type: 'select',
    label: 'Onde você mais percebe a queda ou rarefação?',
    options: [
      { value: 'Entradas (testa)', label: 'Entradas (testa)' },
      { value: 'Coroa (topo da cabeça)', label: 'Coroa (topo da cabeça)' },
      { value: 'Todo o couro cabeludo', label: 'Todo o couro cabeludo' },
      { value: 'Lateral e nuca', label: 'Lateral e nuca' },
      { value: 'Não tenho queda específica', label: 'Não tenho queda específica' },
    ],
    required: true,
    helperText: 'O padrão ajuda a identificar o tipo de alopécia.',
    evidenceNote: 'Calvície androgenética masculina começa nas entradas e coroa.',
    justification: 'Localização é crucial para diferenciar tipos de alopécia.',
  },
  {
    name: 'intensidade_queda',
    type: 'select',
    label: 'Como você avalia a intensidade da queda?',
    options: [
      { value: 'Leve', label: 'Leve (alguns fios no travesseiro/pente)' },
      { value: 'Moderada', label: 'Moderada (queda visível ao pentear)' },
      { value: 'Intensa', label: 'Intensa (muitos fios, rarefação visível)' },
      { value: 'Muito intensa', label: 'Muito intensa (áreas sem cabelo)' },
    ],
    required: true,
    helperText: 'Avalie baseado no que você observa no dia a dia.',
    justification: 'Intensidade ajuda a calibrar urgência e tipo de tratamento.',
  },
  {
    name: 'info_contraindicacoes_capilar',
    type: 'info',
    icon: '🛡️',
    highlightTag: 'Segurança',
    label: 'Algumas condições precisam de avaliação especial',
    description: 'Vamos verificar se há algo que exija cuidado antes do tratamento:',
    bullets: [
      'Seu relatório será personalizado com base nas suas respostas.',
      'Em caso de dúvida, o médico avaliará no momento da consulta.',
    ],
    justification: 'Educação e segurança antes de contraindicações.',
  },
  {
    name: 'contraindicacoes_capilares',
    type: 'multiselect',
    label: 'Você tem ou já teve alguma dessas condições?',
    options: [
      { value: 'alergia_minoxidil', label: 'Alergia conhecida a minoxidil' },
      { value: 'dermatite_ativa', label: 'Dermatite ou ferida no couro cabeludo' },
      { value: 'cardiopatia_grave', label: 'Doença cardíaca grave não controlada' },
      { value: 'gestacao_amamentacao', label: 'Gestação ou amamentação' },
      { value: 'nenhuma', label: 'Nenhuma dessas' },
    ],
    required: true,
    helperText: 'Essas informações são essenciais para sua segurança.',
    evidenceNote: 'Minoxidil é contraindicado em cardiopatia grave e gestação.',
    justification: 'Critério de segurança para tratamento capilar.',
  },
  {
    name: 'preferencia_capilar',
    type: 'select_cards',
    label: 'Se precisar de tratamento, qual abordagem te parece melhor?',
    helperText: 'É só uma preferência inicial. A decisão final será sempre do médico.',
    required: true,
    justification: 'Usada pela IA para personalizar o relatório e recomendações.',
    cardOptions: [
      {
        value: 'minoxidil',
        title: 'Minoxidil tópico',
        subtitle: 'Maior evidência de eficácia para calvície androgenética.',
        badge: '📊 Evidência consolidada',
      },
      {
        value: 'suplementos',
        title: 'Suplementos orais',
        subtitle: 'Nutrição do folículo com vitaminas e minerais.',
        badge: '🌿 Abordagem natural',
      },
      {
        value: 'combinado',
        title: 'Combinado (tópico + oral)',
        subtitle: 'Abordagem integrativa para melhores resultados.',
        badge: '⚡ Potencial máximo',
      },
      {
        value: 'nao_sei',
        title: 'Prefiro que o médico escolha',
        subtitle: 'Quero que o especialista indique a melhor opção.',
        badge: '🩺 Decisão guiada',
      },
    ],
  },
  {
    name: 'info_acompanhamento',
    type: 'info',
    icon: '🤝',
    highlightTag: 'Segurança e apoio',
    label: 'Você não faz esse caminho sozinho',
    description:
      'Tratamentos capilares funcionam melhor quando combinam suplementação, acompanhamento médico e ajustes de estilo de vida.',
    bullets: [
      'Suplementos são formulados com nutrientes específicos para saúde capilar',
      'Acompanhamento com dermatologista/tricologista para identificar causas e ajustar tratamento',
    ],
    justification: 'Reforça segurança e autoridade médica.',
  },
];
