import type { Step } from '@/types/triagem';
import { stepAceitaTermos } from '../shared/consentimento';
import { stepIdadeFaixa, stepSexo } from '../shared/dadosBasicos';

export const perguntasImunidade: Step[] = [
  stepAceitaTermos,
  stepIdadeFaixa,
  stepSexo,
  {
    name: 'infeccoes_recorrentes',
    type: 'select',
    label: 'Com que frequência você fica doente (gripes, resfriados)?',
    options: [
      { value: 'Mais de 4x por ano', label: 'Mais de 4x por ano' },
      { value: '3-4x por ano', label: '3–4x por ano' },
      { value: '1-2x por ano', label: '1–2x por ano' },
      { value: 'Raramente', label: 'Raramente' },
    ],
    required: true,
    helperText: 'Infecções recorrentes podem indicar baixa imunidade.',
    justification: 'Frequência de infecções é marcador importante de imunidade.',
  },
  {
    name: 'fadiga_constante',
    type: 'select',
    label: 'Você sente fadiga constante ou cansaço excessivo?',
    options: [
      { value: 'Sim, sempre', label: 'Sim, sempre' },
      { value: 'Sim, frequentemente', label: 'Sim, frequentemente' },
      { value: 'Ocasionalmente', label: 'Ocasionalmente' },
      { value: 'Não', label: 'Não' },
    ],
    required: true,
    helperText: 'Fadiga pode estar relacionada à baixa imunidade.',
    justification: 'Fadiga é sintoma importante de problemas imunológicos.',
  },
  {
    name: 'doencas_cronicas',
    type: 'multiselect',
    label: 'Você tem alguma dessas condições?',
    options: [
      { value: 'Diabetes', label: 'Diabetes' },
      { value: 'Doenças autoimunes', label: 'Doenças autoimunes' },
      { value: 'Câncer (em tratamento)', label: 'Câncer (em tratamento)' },
      { value: 'Nenhuma dessas', label: 'Nenhuma dessas' },
    ],
    required: true,
    helperText: 'Essas condições podem afetar imunidade.',
    justification: 'Doenças crônicas são fatores importantes para imunidade.',
  },
  {
    name: 'uso_imunossupressores',
    type: 'select',
    label: 'Você usa medicamentos imunossupressores?',
    options: [
      { value: 'Sim', label: 'Sim' },
      { value: 'Não', label: 'Não' },
      { value: 'Não sei', label: 'Não sei' },
    ],
    required: true,
    helperText: 'Imunossupressores reduzem resposta imune.',
    justification: 'Medicamentos são fatores importantes para imunidade.',
  },
  {
    name: 'qualidade_sono',
    type: 'select',
    label: 'Como você avalia a qualidade do seu sono?',
    options: [
      { value: 'Excelente', label: 'Excelente' },
      { value: 'Boa', label: 'Boa' },
      { value: 'Regular', label: 'Regular' },
      { value: 'Ruim', label: 'Ruim' },
      { value: 'Muito ruim', label: 'Muito ruim' },
    ],
    required: true,
    helperText: 'Sono ruim reduz imunidade.',
    justification: 'Sono é fundamental para imunidade.',
  },
  {
    name: 'info_contraindicacoes_imunidade',
    type: 'info',
    icon: '🛡️',
    highlightTag: 'Segurança',
    label: 'Algumas condições precisam de avaliação especial',
    description: 'Vamos verificar se há algo que exija cuidado antes do tratamento:',
    bullets: [
      'Seu relatório será personalizado com base nas suas respostas.',
      'Em caso de dúvida, o médico avaliará no momento da consulta.',
    ],
    justification: 'Educação e segurança antes de contraindicações.',
  },
  {
    name: 'contraindicacoes_imunidade',
    type: 'multiselect',
    label: 'Você tem ou já teve alguma dessas condições?',
    options: [
      { value: 'imunodeficiencia', label: 'Imunodeficiência primária ou HIV' },
      { value: 'transplante', label: 'Transplante de órgão (imunossupressão)' },
      { value: 'alergia_vitamina', label: 'Alergia conhecida a vitamina C, D ou zinco' },
      { value: 'doenca_renal_grave', label: 'Doença renal grave (doses altas de vitaminas)' },
      { value: 'gestacao_amamentacao', label: 'Gestação ou amamentação' },
      { value: 'nenhuma', label: 'Nenhuma dessas' },
    ],
    required: true,
    helperText: 'Essas informações são essenciais para sua segurança.',
    justification: 'Critério de segurança para suplementação imunológica.',
  },
  {
    name: 'preferencia_imunidade',
    type: 'select_cards',
    label: 'Se precisar de tratamento, qual abordagem te parece melhor?',
    helperText: 'É só uma preferência inicial. A decisão final será sempre do médico.',
    required: true,
    justification: 'Usada pela IA para personalizar o relatório e recomendações.',
    cardOptions: [
      {
        value: 'vitaminas',
        title: 'Vitaminas C, D e Zinco',
        subtitle: 'Nutrientes essenciais para sistema imune.',
        badge: '💊 Evidência consolidada',
      },
      {
        value: 'probioticos',
        title: 'Probióticos',
        subtitle: 'Microbiota intestinal influencia imunidade.',
        badge: '🦠 Microbiota',
      },
      {
        value: 'combinado',
        title: 'Vitaminas + probióticos',
        subtitle: 'Abordagem integrativa para melhores resultados.',
        badge: '⚡ Potencial máximo',
      },
      {
        value: 'nao_sei',
        title: 'Prefiro que o médico escolha',
        subtitle: 'Quero que o especialista indique a melhor opção.',
        badge: '🩺 Decisão guiada',
      },
    ],
  },
  {
    name: 'info_acompanhamento',
    type: 'info',
    icon: '🤝',
    highlightTag: 'Segurança e apoio',
    label: 'Você não faz esse caminho sozinho',
    description:
      'Tratamentos de imunidade funcionam melhor quando combinam vitaminas, probióticos e acompanhamento médico.',
    bullets: [
      'Vitaminas C, D e Zinco em doses adequadas fortalecem sistema imune',
      'Acompanhamento médico identifica deficiências e ajusta tratamento',
    ],
    justification: 'Reforça segurança e autoridade médica.',
  },
];
