import type { Step } from '@/types/triagem';
import { stepAceitaTermos } from '../shared/consentimento';
import { stepIdadeFaixa, stepSexo } from '../shared/dadosBasicos';

export const perguntasLibidoMasculina: Step[] = [
  stepAceitaTermos,
  stepIdadeFaixa,
  stepSexo,
  {
    name: 'sintomas_principais',
    type: 'multiselect',
    label: 'Quais sintomas você apresenta?',
    options: [
      { value: 'Diminuição de libido', label: 'Diminuição de libido' },
      { value: 'Falta de energia/disposição', label: 'Falta de energia/disposição' },
      { value: 'Dificuldade de ereção', label: 'Dificuldade de ereção' },
      { value: 'Perda de massa muscular', label: 'Perda de massa muscular' },
      { value: 'Mudanças de humor', label: 'Mudanças de humor' },
      { value: 'Não tenho sintomas, só quero otimizar', label: 'Não tenho sintomas, só quero otimizar' },
    ],
    required: true,
    helperText: 'Escolha todos os sintomas que você sente.',
    justification: 'Sintomas ajudam a identificar padrão e possíveis causas hormonais.',
  },
  {
    name: 'comorbidades',
    type: 'multiselect',
    label: 'Você tem alguma dessas condições?',
    options: [
      { value: 'Diabetes', label: 'Diabetes' },
      { value: 'Hipertensão', label: 'Hipertensão' },
      { value: 'Obesidade', label: 'Obesidade' },
      { value: 'Problemas de tireoide', label: 'Problemas de tireoide' },
      { value: 'Nenhuma dessas', label: 'Nenhuma dessas' },
    ],
    required: true,
    helperText: 'Essas condições podem afetar saúde hormonal.',
    justification: 'Comorbidades são fatores importantes para saúde hormonal.',
  },
  {
    name: 'qualidade_sono',
    type: 'select',
    label: 'Como você avalia a qualidade do seu sono?',
    options: [
      { value: 'Excelente', label: 'Excelente' },
      { value: 'Boa', label: 'Boa' },
      { value: 'Regular', label: 'Regular' },
      { value: 'Ruim', label: 'Ruim' },
      { value: 'Muito ruim', label: 'Muito ruim' },
    ],
    required: true,
    helperText: 'Sono ruim reduz produção de testosterona.',
    justification: 'Sono é fundamental para produção hormonal.',
  },
  {
    name: 'atividade_fisica',
    type: 'select',
    label: 'Com que frequência você pratica atividade física?',
    options: [
      { value: 'Diariamente', label: 'Diariamente' },
      { value: '3-4x por semana', label: '3–4x por semana' },
      { value: '1-2x por semana', label: '1–2x por semana' },
      { value: 'Raramente', label: 'Raramente' },
      { value: 'Nunca', label: 'Nunca' },
    ],
    required: true,
    helperText: 'Exercício regular aumenta testosterona.',
    justification: 'Exercício é estratégia importante para saúde hormonal.',
  },
  {
    name: 'info_contraindicacoes_libido',
    type: 'info',
    icon: '🛡️',
    highlightTag: 'Segurança',
    label: 'Algumas condições precisam de avaliação especial',
    description: 'Vamos verificar se há algo que exija cuidado antes do tratamento:',
    bullets: [
      'Seu relatório será personalizado com base nas suas respostas.',
      'Em caso de dúvida, o médico avaliará no momento da consulta.',
    ],
    justification: 'Educação e segurança antes de contraindicações.',
  },
  {
    name: 'contraindicacoes_libido',
    type: 'multiselect',
    label: 'Você tem ou já teve alguma dessas condições?',
    options: [
      { value: 'cancer_prostata', label: 'Câncer de próstata ou suspeita' },
      { value: 'policitemia', label: 'Policitemia ou histórico de trombose' },
      { value: 'insuficiencia_hepatica', label: 'Insuficiência hepática grave' },
      { value: 'infertilidade_ativa', label: 'Tentando engravidar parceira' },
      { value: 'alergia_maca_tribulus', label: 'Alergia a maca ou tribulus' },
      { value: 'nenhuma', label: 'Nenhuma dessas' },
    ],
    required: true,
    helperText: 'Essas informações são essenciais para sua segurança.',
    justification: 'Critério de segurança para saúde masculina.',
  },
  {
    name: 'preferencia_libido',
    type: 'select_cards',
    label: 'Se precisar de tratamento, qual abordagem te parece melhor?',
    helperText: 'É só uma preferência inicial. A decisão final será sempre do médico.',
    required: true,
    justification: 'Usada pela IA para personalizar o relatório e recomendações.',
    cardOptions: [
      {
        value: 'maca',
        title: 'Maca peruana',
        subtitle: 'Suplemento com evidência para libido e energia.',
        badge: '🌿 Abordagem natural',
      },
      {
        value: 'tribulus',
        title: 'Tribulus terrestris',
        subtitle: 'Pode auxiliar suporte hormonal e desempenho.',
        badge: '💪 Suporte hormonal',
      },
      {
        value: 'combinado',
        title: 'Maca + tribulus + zinco',
        subtitle: 'Abordagem integrativa para melhores resultados.',
        badge: '⚡ Potencial máximo',
      },
      {
        value: 'nao_sei',
        title: 'Prefiro que o médico escolha',
        subtitle: 'Quero que o especialista indique a melhor opção.',
        badge: '🩺 Decisão guiada',
      },
    ],
  },
  {
    name: 'info_acompanhamento',
    type: 'info',
    icon: '🤝',
    highlightTag: 'Segurança e apoio',
    label: 'Você não faz esse caminho sozinho',
    description:
      'Tratamentos de saúde masculina funcionam melhor quando combinam suplementação, estilo de vida e acompanhamento médico.',
    bullets: [
      'Suplementos como maca e tribulus ajudam a regular testosterona',
      'Acompanhamento médico avalia hormônios e ajusta tratamento',
    ],
    justification: 'Reforça segurança e autoridade médica.',
  },
];
