import type { Step } from '@/types/triagem';
import { stepAceitaTermos } from '../shared/consentimento';
import { stepIdadeFaixa, stepSexo } from '../shared/dadosBasicos';

export const perguntasSono: Step[] = [
  stepAceitaTermos,
  stepIdadeFaixa,
  stepSexo,
  {
    name: 'objetivo_sono',
    type: 'select',
    label: 'Qual é seu principal problema com o sono?',
    options: [
      { value: 'Dificuldade para adormecer', label: 'Dificuldade para adormecer' },
      { value: 'Acordo várias vezes durante a noite', label: 'Acordo várias vezes durante a noite' },
      { value: 'Acordo muito cedo e não consigo voltar a dormir', label: 'Acordo muito cedo e não consigo voltar a dormir' },
      { value: 'Sono não reparador (acordo cansado)', label: 'Sono não reparador (acordo cansado)' },
      { value: 'Todos os anteriores', label: 'Todos os anteriores' },
    ],
    required: true,
    helperText: 'Escolha o problema que mais te incomoda.',
    justification: 'Definir o problema principal ajuda a IA a ajustar o foco do relatório.',
  },
  {
    name: 'tempo_insonia',
    type: 'select',
    label: 'Há quanto tempo você tem problemas para dormir?',
    options: [
      { value: 'Menos de 1 mês', label: 'Menos de 1 mês' },
      { value: '1-3 meses', label: '1–3 meses' },
      { value: '3-6 meses', label: '3–6 meses' },
      { value: 'Mais de 6 meses', label: 'Mais de 6 meses' },
      { value: 'Anos', label: 'Anos' },
    ],
    required: true,
    helperText: 'Isso ajuda a entender se é algo recente ou crônico.',
    justification: 'Tempo de evolução diferencia insônia aguda de crônica.',
  },
  {
    name: 'horas_sono',
    type: 'select',
    label: 'Quantas horas você dorme por noite?',
    options: [
      { value: 'Menos de 4 horas', label: 'Menos de 4 horas' },
      { value: '4-5 horas', label: '4–5 horas' },
      { value: '5-6 horas', label: '5–6 horas' },
      { value: '6-7 horas', label: '6–7 horas' },
      { value: '7-8 horas', label: '7–8 horas' },
      { value: 'Mais de 8 horas', label: 'Mais de 8 horas' },
    ],
    required: true,
    helperText: 'A maioria das pessoas precisa de 7-9 horas.',
    justification: 'Duração do sono é marcador importante de qualidade.',
  },
  {
    name: 'ronco_apneia',
    type: 'select',
    label: 'Você ronca ou alguém já disse que você para de respirar durante o sono?',
    options: [
      { value: 'Sim, ronco alto e frequente', label: 'Sim, ronco alto e frequente' },
      { value: 'Sim, ronco leve', label: 'Sim, ronco leve' },
      { value: 'Sim, já disseram que paro de respirar', label: 'Sim, já disseram que paro de respirar' },
      { value: 'Não sei', label: 'Não sei' },
      { value: 'Não', label: 'Não' },
    ],
    required: true,
    helperText: 'Apneia do sono pode causar sono não reparador e precisa de avaliação médica.',
    justification: 'Ronco e apneia são red flags importantes.',
  },
  {
    name: 'info_contraindicacoes_sono',
    type: 'info',
    icon: '🛡️',
    highlightTag: 'Segurança',
    label: 'Algumas condições precisam de avaliação especial',
    description: 'Vamos verificar se há algo que exija cuidado antes do tratamento:',
    bullets: [
      'Seu relatório será personalizado com base nas suas respostas.',
      'Em caso de dúvida, o médico avaliará no momento da consulta.',
    ],
    justification: 'Educação e segurança antes de contraindicações.',
  },
  {
    name: 'contraindicacoes_sono',
    type: 'multiselect',
    label: 'Você tem ou já teve alguma dessas condições?',
    options: [
      { value: 'apneia_diagnosticada', label: 'Apneia do sono diagnosticada (não tratada)' },
      { value: 'narcolepsia', label: 'Narcolepsia ou hipersonia' },
      { value: 'epilepsia', label: 'Epilepsia não controlada' },
      { value: 'gestacao_amamentacao', label: 'Gestação ou amamentação' },
      { value: 'medicamentos_sono', label: 'Uso crônico de medicamentos para dormir' },
      { value: 'nenhuma', label: 'Nenhuma dessas' },
    ],
    required: true,
    helperText: 'Essas informações são essenciais para sua segurança.',
    justification: 'Critério de segurança para tratamento do sono.',
  },
  {
    name: 'preferencia_sono',
    type: 'select_cards',
    label: 'Se precisar de tratamento, qual abordagem te parece melhor?',
    helperText: 'É só uma preferência inicial. A decisão final será sempre do médico.',
    required: true,
    justification: 'Usada pela IA para personalizar o relatório e recomendações.',
    cardOptions: [
      {
        value: 'melatonina',
        title: 'Melatonina e fitoterápicos',
        subtitle: 'Regulam o ciclo circadiano de forma natural.',
        badge: '🌙 Abordagem natural',
      },
      {
        value: 'higiene_sono',
        title: 'Higiene do sono + suplementos',
        subtitle: 'Ajustes de hábitos e suplementação combinados.',
        badge: '🛏️ Hábitos + suplementos',
      },
      {
        value: 'avaliacao_completa',
        title: 'Avaliação médica completa',
        subtitle: 'Quero que o médico identifique causas e indique o melhor.',
        badge: '🩺 Decisão guiada',
      },
      {
        value: 'nao_sei',
        title: 'Prefiro que o médico escolha',
        subtitle: 'Quero que o especialista indique a melhor opção.',
        badge: '✨ Recomendação do médico',
      },
    ],
  },
  {
    name: 'info_acompanhamento',
    type: 'info',
    icon: '🤝',
    highlightTag: 'Segurança e apoio',
    label: 'Você não faz esse caminho sozinho',
    description:
      'Tratamentos para sono funcionam melhor quando combinam suplementação, higiene do sono e acompanhamento médico.',
    bullets: [
      'Suplementos com melatonina e fitoterápicos ajudam a regular o ciclo circadiano',
      'Acompanhamento médico identifica causas específicas (apneia, ansiedade, etc.)',
    ],
    justification: 'Reforça segurança e autoridade médica.',
  },
];
